[package]
name = "weather"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.38", features = ["derive"] }
dotenv = "0.15.0"
reqwest = "0.12.15"
tokio = { version = "1.45.0", features = ["full"] }
